apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-application
  namespace: argocd
spec:
  project: default
  source:
    chart: vaultwarden
    repoURL: https://charts.gabe565.com
    targetRevision: 0.12.1
    helm:
      releaseName: vaultwarden
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
