apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  sources:
  - repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: apps/media/transmission
