apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  sources:
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/common
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/prowlarr
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/proxy
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/rd-downloader
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/radarr
