controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        image:
          repository: qmcgaw/gluetun
          pullPolicy: Always
          tag: v3
        securityContext:
          privileged: true
          capabilities:
            add: [ "NET_ADMIN" ]
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
service:
  main:
    controller: main
    nameOverride: svc
    ports:
      http:
        port: 8888
persistence:
  secret:
    enabled: true
    type: secret
    name: wg-env
    advancedMounts:
      main:
        wireguard:
        - path: /gluetun/wireguard
          readOnly: false
