controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        image:
          repository: flaresolverr/flaresolverr
          pullPolicy: Always
          tag: latest
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8191
