controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        image:
          repository: linuxserver/jackett
          pullPolicy: IfNotPresent
          tag: latest
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
      wireguard:
        image:
          repository: linuxserver/wireguard
          pullPolicy: IfNotPresent
          tag: latest
        securityContext:
          privileged: true # Needed to configure WireGuard interfaces
        env:
        - name: TZ
          value: "Asia/Kolkata" # Set your timezone
        - name: PEERDNS
          value: "auto"
        - name: INTERNAL_SUBNET
          value: "10.12.12.0/24"
      flare-solver:
        image:
          repository: flaresolverr/flaresolverr
          pullPolicy: IfNotPresent
          tag: latest
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 9117
  flare-solverr:
    controller: main
    ports:
      http:
        port: 8191
persistence:
  secret:
    enabled: true
    type: secret
    name: wg-env
    advancedMounts:
      main:
        wireguard:
        - path: /config/wg_confs
          readOnly: false
  config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: jackett-pvc
    advancedMounts:
      main:
        main:
        - path: /config
          readOnly: false
