image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: latest

controller:
  strategy: RollingUpdate

env:
- name: PUID
  valueFrom:
    configMapKeyRef:
      key: PUID
- name: PGID
  valueFrom:
    configMapKeyRef:
      key: PGID
- name: TZ
  valueFrom:
    configMapKeyRef:
      key: TZ

service:
  main:
    ports:
      http:
        port: 6500

persistence:
  data:
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/config/transmission
    globalMounts:
    - path: /data/db
  downloads:
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads
    globalMounts:
    - path: /data/downloads
