image:
  repository:  rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: latest
controller:
  strategy: RollingUpdate
service:
  main:
    ports:
      http:
        port: 6500
persistence:
  transmission:
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/config/transmission
    globalMounts:
      - path: /data/db
