image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: latest

controller:
  strategy: RollingUpdate

env:
- name: PUID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PUID
- name: PGID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PGID
- name: TZ
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: TZ

service:
  main:
    ports:
      http:
        port: 6500

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteMany
    globalMounts:
    - path: /data/db
      readOnly: false
  nfs-media-incomplete:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads/incomplete
    globalMounts:
    - path: /nfs-media/downloads/incomplete
      readOnly: false
  nfs-media-complete:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads/complete
    globalMounts:
    - path: /nfs-media/downloads/complete
      readOnly: false
