image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: latest

controller:
  strategy: RollingUpdate

env:
- name: PUID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: PUID
- name: PGID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: PGID
- name: TZ
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: TZ

service:
  main:
    ports:
      http:
        port: 6500

persistence:
  test:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd
    globalMounts:
      - path: /data/test
        readOnly: false
  data:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/config/transmission
    globalMounts:
      - path: /data/db
        readOnly: false
  downloads:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads
    globalMounts:
      - path: /data/downloads
        readOnly: false
