image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: latest

controller:
  strategy: RollingUpdate

env:
- name: PUID
  value: 1000
- name: PGID
  value: 1000
- name: TZ
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: TZ

service:
  main:
    ports:
      http:
        port: 6500

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteMany
    globalMounts:
    - path: /data/db
      readOnly: false
  nfs-media:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads
    globalMounts:
    - path: /nfs-media/downloads
      readOnly: false
