image:
  repository: rogerfar/rdtclient
  pullPolicy: IfNotPresent
  tag: sha-d5aaad8

controller:
  strategy: RollingUpdate

env:
- name: PUID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PUID
- name: PGID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PGID
- name: TZ
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: TZ

service:
  main:
    ports:
      http:
        port: 6500

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteOnce
    globalMounts:
    - path: /data/db
      readOnly: false
  nfs-movies:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/movies
    globalMounts:
    - path: /media/movies
  nfs-downloads:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads
    globalMounts:
    - path: /media/downloads
