apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vautlwarden-application
  namespace: argocd
spec:
  project: default
  source:
    chart: vaultwarden
    repoURL: https://charts.gabe565.com
    targetRevision: 0.12.1
    helm:
      releaseName: vaultwarden
      valuesFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
