apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-application
  namespace: argocd

spec:
  project: default
  sources:
  - repoURL: https://github.com/nfl-nzr/homelab
    path: apps/general/vaultwarden/pre-reqs
  - chart: vaultwarden
    repoURL: https://charts.gabe565.com
    targetRevision: 0.12.1
    helm:
      releaseName: vaultwarden
      valueFiles:
      - $values/apps/general/vaultwarden/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
