# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
configMapGenerator:
- name: common-conf
  namespace: media
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Asia/Kolkata
