---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-env
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgCKJ0ruqoi2V+3qZSK1Alx/lbX1FRSg0wJo1eAxCUUtb0qd2Iril+xndFqDOJKR8wY7oiiZCXvU22oYwfU3rMJg/dWyS9kxruy8O0NxT+0Jm5MgIkL1bV2b4sKvNn+9zIk03pcDnUn54duhY9oKvDbDxMNrUXP5qVCEKnzoyh1oKrl2W5w5hsho54R5eeAOtHSoYnjAeA713Yeta7kM+qn2kZCZm4Tf+npRIix2iG2MaSx4pqwRgFb4nNi89Or6xajQoFEjHy/s5+pvoJS+h9ZKySTN3w8uLo1pQDgJljKTyQBHiYgYPFOlR3Yn/iJTFb8UHc8ogdo7iEcG0xtF0Z+Bs6fh6TGtl/ac0MCZ2MGBqnmhdtqmqFGJ9/73SMpmNa+KaOt74PNNP7Rpezz923iSoQ0HXdaYlKD2phKZz2EgnrxIU5cRLkwgfczuAb4h8fO3JP/TmwQro0SQs73FVMuQdgxtsV/WUPOZ9zuJxljtwMtXF1ts/Gyl0AJvJK/gQC7g7mIQw4bifX19yhd96fW5EDFuT1/YGX9LsmHIO7ZpxiiWUqVBxysGHQrH5xbJyTzJgTTis6t2u4AcGYKJ+fX6jamjjme/7um9H9asjln1pHtizUoYBihfHKfc1S13GMxxK5YLuDcs/ENSde4xOHjGlLRiFWYhurOKGZTXQ169Mql06/rdON9Vme1ShLxUBATTn5XK08NmynwFGrUR88eyXLy7pNDpkaIL/O8Q1WHJVDIuiy79QN7Xq3loogglfWMjxmuA9Btx77p42DyPKQrzr2jr9DRrZ49pPpOHs96jiHqNICt2F+f6CTkPME9eEVCK5lcqnlgPkuVN0WXb0ysURUHBCXYXSa81MdM8EuyYoZHlF8c/s/JHbVPUecL3RLDGLLrjkDmiruSUkBSR53lSBvrGVHRJ9AfHl85G5z+DjVAjmbfJcmljO3uaOZmwvZPb7ojd2cHeklHE1XiMP6d1OYsuyIdcrIPYzkTA53Pjil66QM535ewp4pRfmoSBN6285JA4h8lLwMA29SsBew==
  template:
    metadata:
      creationTimestamp: null
      name: wg-env
      namespace: media
    type: Opaque
