---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-env
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgCK/Kl8k4YE8lsM8RWPq7ZgGFRRsnK8ypNiORXTQMX8nZ6mjlt0CqezsydNPppbwh/Cj3KA3SGvfReM8Zm3e9vnbTMb6pIDwxFpaV0l3mo1rwfMcKxeuSYvwL/jRGPHl5MrLwFY/JzSX/99jEFbfrrHwtKgN8zSY1oq0RyBpQgVeJAo4OOGQo7ilpdV6trxpIiKnyXG4XzRxXa8sGX6xv2NDNc/IL7q5jQyQbQKY0UiDcwo2gfb+qNPvhWRJLUl/P+9NoPhUleGSpJ+rPEU0LPo+w0/sG6jaxZEIUqgmqbici6nqQTx8d1Q3rO4ZRc3QQagrMcFIRNLkKWZm3GbSbZ9jBbqn5r4ejucZ8qIzvBqE9SVusu9zTGeyU3VL/1uK8kyTJc28l9l6X8iOgE39qLOG5MmzP1887hPof4YKRSb+KOqbjpJWar7v1Piw84/f919Ip5hid+Mj0Jga32yYo+RcpzOI/70e7P1ld9R7sURKSiKPxh74Xgg4PbuoS8ysQ2stuveDetMyKPlQNEFuqHPU3LTnAui4wLE6NzwOjUe0pGHczt3UUA+tHnYklf37Zr8TW2JbAtdJ7qkpSiA5FjZs50C+VctXF1wf+wpz5taHxxh8Xk80/Z0hNkEBU3ip36w99bJS9C3xrTu4lMC+F5ISmEQ1ci1NX46BkcdkNU3ldkb/uRWHlOkysy2ofAzb3DvYHCaEtXEbUmRJHnL2bE8FGByQvPuWGlq0X77vjSSqJuSDwQKDAuwT++pDEVI6xIKLLjGly+H0UBkQ6fdrkHYDxRI4z8wc7b4LNlTlhfY+7vX4uTABePNl0TWeBe7TUqMi+wxBiO0XJPvDli8ZQef2jBrWvmvURD19c2dD0QCRbGuKpyKLLE035UmC6XNXJBwnFUzlC+5xZIj5WQihF2xGacHBrVuP/6rW/tllyKuGfZ9iEKE71hAMLmXUfNGXETZ2NSZXaaQmKVZM1nRt8VyCRFcfXvIJjDS3u//JWWqSuBdDflvZg7cwrZYKRBoYdObI7faHZg3rTBzg0EqZoGfn7Qso3DIQG4P0lQvsLA=
  template:
    metadata:
      creationTimestamp: null
      name: wg-env
      namespace: media
    type: Opaque
