---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-env
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgAPkBXp6VkKqGtR065TfaxKk70Yz6E1cdprXwK8t7wfcOOmRdzsh3fljfu3oFnZCYK4g6sN0ZEkaw7975suSQwkqHoG90DhVTdE+upwQpYmP2eZlkqMN3t7HT8kKL3OZk7Zej0MQuKB7e54zdUkg/nyJZL5OE0P6OqZKJLLZZ0oNpikDDR3EtKEhBEastbdNIUehgD9Rli+//nkDyUlmWLc06RauBLuZn7XwLFexSc0/MJy+dJRlZfyNGyptoFDy985hJg+PDAAuxCjw8onzz4S4i8Ax5X/nIk96i7qiJU76ch8jK6C+GtBjIHoMYPECFjITAiwTW2dFmbBA5f+ADHXMpkRGg/2Wl5SKRiJ45kEWb+GF+zM3HS6nAycpcRmWM6LY6Eqywb+mP+dbNPtnRBN8U2R2U3+8+e4UmpOkLFZlkLtL+p0qOa0fteYoZ+CPYlGjiiKB1uGCsoPBZ7BeapEISTS4SyDpl6GtBUde2HI71zH4GeraEzpv4nFVYKTsHWgc3kItMpcp/M5C0O+PtT0rusLB06Nq+VYDuQ+cgUa8/2L4Th3GOg45Et+n2Sqe0ZLvu+IDXz0/QOGhNrQ8KcCSxWlwQvGjlu5JUiLNEuvKjrSCzWvUlEG7urKAAK3LGpRZ4F8kNpslXzixJ8bpYAulhzW+1SHlfKDaLmsQdzwqHP5IWwvR3UIuB6NZX190GiyNluT6lijoIcT+VP0RcY+8kQjZy4+foJGVzngfbPBB6LOGydisiYBibP1doXb87TYMl8MZNBZA8PxqUcKSDB1GB+CutmgeZmnQvzuSCDYCZYkpjeZ0ZGkjczgs9XSskVYNpEomeNE0+JFbwgUDLRh0PfE6pdKNvB+45lD5XeOd43sKfHdTCB2CfaoSbZXd44HpjkXwBVUVGJV96S0pYaf9PXWcW2eSq1n3lTI8K2wggsSvn/o3e97ZrirkpHQk3JaSjVD94k8Y/QVFLibfoF9FnKTOAfhPXxd6jQxjQza3P58sqG4VDXK5VjWpr83eDUH0ArI1S5JreBG/yrQcUE=
  template:
    metadata:
      creationTimestamp: null
      name: wg-env
      namespace: media
    type: Opaque
