---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-env
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgB3bIOYake66mmh7CvZ8KgMeUW8/P0KUXbmMymAVmMcstLLkc64BAupzPdA77pEhVeDxa0Hn6WDx0oPe8h5QGGNiJ5N9BaKjRVddf1/RNPmgViv5zlVMSOIJDTtvcFuEm/eu/PgmvfrJBpqgE18b77bDV8M/6nEXOp0mtWJ4Rtn7VqfmetdnP2BwnRWQqyXAsWzsDlsk0HNOOXCjqOsRciYuzTV1H6TxSoEJNVnpfsvSCRxN1Qk08SvxdDMrIyZhMyuF2YxhPlaPiulSeGWgmeKyJL65uQ7z43PsTKFmgyG3JsVFt23xl0DOX2ElT08eDe4dskwirqS9mV/1Tq+uJBYwJa6ip7OMqHl2DjB9UBIg/jH71QgK788HyAE5jNI47xqDv4dyiKJFrOk8MhZHHrmzEekbPrzaTcA5xoq6/7VEU6+34urHCSerhfmxyJGJTEWVtExlKWklaH06rrYlMBYZT9LXh0gSo3JW6Bd/lF7XIqj68479x9f7o6PTKwY163A6X8paxbHDdDqoEniR6VL6137UQcP0tvAAX/mixgnDxntheibiLnq6FTvM7649cHiHKYCq7eYPIVaCME2mnwiifuxrBp7Qr6Ft0dSflNGqSVh+NLCEDXqihoXupUCEYNeqQkse6mqcnkHY8mcQ22NVoDhQjceBPMXJPp//ARAFzp6Vi/qOgPf4lQDiPfO2LTFqRASaJlgF9iG8rVSHYV1ooTNJjrKXDdnj2l88RZf4QDQYvNFgM08xlP5r2soGaGQTYInkn0rwxr8hBbOOSt93TOCqAf+J5Tc0ityff+A6MBMm7SDNHJqQ4/JkqVqDULQCjkZC5tG4j/n7xrvCRuissqWAanrTNmB5JnfljLgRQSiUnBqfmm3W/MTzf7tFUvTg6BMGaGXgocivfMIQEK3KjBS5h9ET5eY0Oz+EY5pkqQKCWXzEVM02keqlqYVhNmKguOavq6X24WoNGKls8Zi0IPd7TaXqgWzD6aqBWSAQ5u9O06DEINO38NTAWfIX5Og4vX5cfgHahGNGiG3
  template:
    metadata:
      creationTimestamp: null
      name: wg-env
      namespace: media
    type: Opaque
