---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-env
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgCD3BVV2FwWPaQ9CJo+nqpxjb4vNWlxRyt8XgnEzWilwvaxiuSuBDG5Fa2/JjR2EhwGIYkzHipKLLCHZMQy9SK0KpAHC4c8Xk238Gqw8McF/lkDwGIUvOhV83hiZduzzHYwBP0eJbX1Ck//BlNB471/6Stk4V8uZteDPOkS8rYSuZ0kZBQFz3KqfHrL0vS6ltgDylqBDAeLSyeIkqMck6tx8iHvFElliU4QksBEAyWogRFPMQ4Nrbwk3dqBA893WyvVEetbz4JGbT4d3TnrJcFl8uOBgqU57FtCDv4ctgs4Z8oWxKF4YaMz44ZGLjhj8WUIimSM3YmGXLuoTfKImCljbq8EUUtHd1enAiftGiv6Lk/xoR+ODrTNNVXK82BflWIdZIhPXesmN/8LzZ0s2A+HpU98klAYT6Y9tVgx43BloxhokwXPLkYMBddizrQGU5DzUIOA8LgpCh/CDFwwQgxWArgfWHjyAeNWp+buLKc0owOW3wCMs7als5iBIqx+stM3qYt6Wb4Hiq41oBcDK5L1oDHzvK1SyZtSP6oTxvYnjmDbl6U2GstSLexOfVOQr4YSBeJk8LCZ1FiA/jL8B/89TWR1PJZxCYz0eFSNdDeg9FQ9vpAOPzRNb8xKjDZjqOgoieFG9g5DF7WKdyC3jCmhXrZm3TJQ4jPk3tvWCADwXwz9Lsehhj67sYTFPMLkO4H5BBRf/lxbgo2KS8TpqGhPyau7XI9DX/HZcHGZ6GKz5rASmf2vd+IZKAevtYmRhkoP8dgpEhSRHyyua6WKrK2Q8Cp0O0zEcIQbqySJsJe8+b+nx9MRV76kuA1YZPDFlN3urMKzpwdOtXWWmHRXiEIjnWSmKpyMBhr1myKwZcsthxOsMjj5ESCwbo9AZNhJn1nkAPiVsRYxu4xLeGb4/ecNtX00YUKbVPHdxP9ZK4L2Ma09vMZzYoxEOSrU6WU9y7miWF9ofvaGTiKwUVM+xPfHz27fs/Np/ZfXfTrFdmZwcxgspmj1Z3JrYnd48eZBsXxiJP8sW0PNNJMAETaUtEfqrQKZUwb6kFmsC1fKZQk=
  template:
    metadata:
      creationTimestamp: null
      name: wg-env
      namespace: media
    type: Opaque
