apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  releaseName: test-release
  namespace: freshrss
  version: 0.1.0
  valuesFile: values.yaml
