apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml

helmCharts:
- name: vaultwarden
  repo: https://charts.gabe565.com
  releaseName: vaultwarden
  namespace: vaultwarden
  version: 0.1.0
  valuesFile: values.yaml
