apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: vaultwarden
data:
  adminToken: JGFyZ29uMmkkdj0xOSRtPTE2LHQ9MixwPTEkVFRZMGVsQmxTMEoyYWtwNFQwRklidyR1bXJYd1BlL1JtNjVjVGZxV2dUU253
