apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
- pvc.yaml

helmCharts:
- name: app-template
  repo: https://bjw-s.github.io/helm-charts/
  releaseName: radarr
  version: 0.1.0
  valuesFile: values.yaml
