controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        image:
          repository: linuxserver/radarr
          pullPolicy: Always
          tag: latest
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
service:
  main:
    controller: main
    nameOverride: svc
    ports:
      http:
        port: 7878

ingress:
  main:
    enabled: true
    className: "nginx"
    hosts:
    - host: radarr.wg
      paths:
      - path: /
        service:
          identifier: main
          port: http

persistence:
  radarr-config:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: radarr-pvc
    advancedMounts:
      main:
        main:
        - path: /config
          readOnly: false
  nfs-movies:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/movies
    globalMounts:
    - path: /mnt/hdd/media/movies
      readOnly: false
  nfs-downloads:
    enabled: true
    type: nfs
    server: 192.168.1.115
    path: /mnt/hdd/media/downloads
    globalMounts:
    - path: /mnt/hdd/media/downloads
      readOnly: false
