image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: latest

controller:
  strategy: RollingUpdate

env:
- name: PUID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PUID
- name: PGID
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: NFS_PGID
- name: TZ
  valueFrom:
    configMapKeyRef:
      name: common-conf
      key: TZ

service:
  main:
    ports:
      http:
        port: 7878

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteOnce
