controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        dependsOn: vpn
        image:
          repository: linuxserver/prowlarr
          pullPolicy: IfNotPresent
          tag: latest
service:
  main:
    ports:
      http:
        port: 9696
