image:
  repository: linuxserver/prowlarr
  pullPolicy: IfNotPresent
  tag: latest
controller:
  strategy: RollingUpdate
env:
- name: PUID
  value: "1000"
- name: PGID
  value: "1000"
service:
  main:
    ports:
      http:
        port: 80
ingress:
  main:
    ingressClassName: "nginx"
    enabled: true
    hosts:
    - host: rss.nfl-nzr.com
      paths:
      - path: /
persistence:
  config:
    enabled: true
    retain: false
    storageClass: "longhorn"
    accessMode: ReadWriteMany
    size: 1Gi
    globalMounts:
    - path: /config
      readOnly: false
