controllers:
  main:
    type: statefulset
    nameOverride: prowlarr-dep
    enabled: true
    statefulset:
      volumeClaimTemplates:
      - name: config
        accessMode: "ReadWriteOnce"
        size: 500Mi
        storageClass: longhorn
        globalMounts:
        - path: /config
          readOnly: false
    containers:
      main:
        image:
          repository: linuxserver/prowlarr
          pullPolicy: IfNotPresent
          tag: latest
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
      flare-solver:
        image:
          repository: flaresolverr/flaresolverr
          pullPolicy: IfNotPresent
          tag: latest

service:
  main:
    controller: main
    nameOverride: svc
    primary: true
    ports:
      http:
        port: 9696
  flare-solverr:
    nameOverride: "svc"
    controller: main
    ports:
      http:
        port: 8191
