controllers:
  main:
    type: deployment
    strategy: Recreate
    enabled: true
    containers:
      main:
        dependsOn: vpn
        image:
          repository: linuxserver/prowlarr
          pullPolicy: IfNotPresent
          tag: latest
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
      vpn:
        image:
          repository: linuxserver/wireguard
          pullPolicy: IfNotPresent
          tag: latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE"]
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: NFS_PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: common-conf
              key: TZ
    initContainers:
      copier:
        image:
          repository: alpine
          tag: latest
        command: ['sh', '-c', "echo 'test' > /config/wg_confs/wg0.conf"]

service:
  main:
    controller: main
    ports:
      http:
        port: 9696

persistence:
  vpn-profile:
    enabled: true
    type: secret
    name: wg-conf
    advancedMounts:
      main:
        vpn:
        - path: /custom
          readOnly: false

    copier:
    - path: /custom
      readOnly: false
  vpn-config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        vpn:
        - path: /config
          readOnly: false
  prowlarr-config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    size: 1Gi
    retain: true
    accessMode: ReadWriteOnce
    advancedMounts:
      main:
        main:
        - path: /config
          readOnly: false
