apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  finalizers:
  - "resources-finalizer.argocd.argoproj.io"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
    - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  sources:
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/common
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/jackett
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/flare-solver
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/rd-downloader
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/radarr
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/plex
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/overseer
  - repoURL: https://github.com/nfl-nzr/homelab.git
    path: apps/media/transmission
